USE [master]
GO

/****** Object:  Database [Visa]    Script Date: 5/14/2019 7:04:29 AM ******/
CREATE DATABASE [Visa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Visa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.NARSINH\MSSQL\DATA\Visa.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Visa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.NARSINH\MSSQL\DATA\Visa_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Visa] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Visa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Visa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Visa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Visa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Visa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Visa] SET ARITHABORT OFF 
GO

ALTER DATABASE [Visa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Visa] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Visa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Visa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Visa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Visa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Visa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Visa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Visa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Visa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Visa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Visa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Visa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Visa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Visa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Visa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Visa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Visa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Visa] SET RECOVERY FULL 
GO

ALTER DATABASE [Visa] SET  MULTI_USER 
GO

ALTER DATABASE [Visa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Visa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Visa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Visa] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Visa] SET  READ_WRITE 
GO


